[package]
name = "wk-371tti-net"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.9"
tera = "1.14.1"
chrono = "0.4"
bytes = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

log = "0.4"