[package]
name = "wk-371tti-net"
version = "0.5.5"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
chrono = "0.4.41"
kurosabi = "0.4.2"
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0.141"
serde = { version = "1.0.219", features = ["derive"] }
dashmap = "6.1.0"
rand = "0.8.0" # 0.9はだめ
base64 = "0.22.1"
tf-idf-vectorizer = "0.3.1"
sha2 = "0.10.9"
argon2 = "0.5.3"
toml = "0.9.5"
log = "0.4.28"
async-trait = "0.1.89"




