base_dir: ./data/
storage_config:
  storage_file: storage.cbor
http_config:
  host: 0.0.0.0
  port: 85
  session_timeout: 30days
  account_timeout: 7days
  cookie_max_age_seconds: 2592000
git_config:
  enable_remote: true
  remote_url: https://github.com/371tti/371tti.net-contents
  remote_branch: main
  user: null
  token: null
cache_config:
  max_memory_bytes: 100MiB
  max_entry_size_bytes: 10MiB
hash_config:
  pepper: e06d25eaf4ff8e363d8a16eba8e3aac1
  memory_kib: 155162
  time_cost: 3
  lanes: 1
