index_server:
  enable: true
  server_bind: 0.0.0.0:81
  server_workers: 8
  server_backlog: 128
  panic_on_error: true
redirect_server:
  enable: true
  server_bind: 0.0.0.0:80
  server_workers: 8
  server_backlog: 128
  panic_on_error: true
path: pages
logger_mode: info
