base_dir: ./data/
storage_config:
  storage_file: storage.cbor
http_config:
  host: 0.0.0.0
  port: 8080
  session_timeout: 30days
  account_timeout: 7days
  cookie_max_age_seconds: 2592000
git_config:
  enable_remote: true
  remote_url: https://github.com/371tti/371tti.net-contents
  remote_branch: main
  user: null
  token: null
hash_config:
  pepper: 788cfc6e9089c7fdf00e93c29f3cbb62
  memory_kib: 152799
  time_cost: 3
  lanes: 4
