domain = "dev.371tti.net"
session_timeout = 2592000
account_timeout = 604800

[database]
url = "mongodb://192.168.0.48:27017/?replicaSet=rs0"
db_name = "371tti_net"

[api_endpoints]
search = "http://localhost:90"

[hash_config]
pepper = "o6uYwqakTmB0WQkyMSOd9Q=="
memory_kib = 151807
time_cost = 3
lanes = 2
