index_server:
  enable: true
  server_bind: 0.0.0.0:80
  server_workers: 8
  server_backlog: 128
  restart_on_panic: true
  max_failures: 5
  failure_count_period_time: 60
  restart_interval: 5
  service_config:
    path: index
transfer_server:
  enable: false
  server_bind: 0.0.0.0:82
  server_workers: 8
  server_backlog: 128
  restart_on_panic: true
  max_failures: 5
  failure_count_period_time: 60
  restart_interval: 5
  service_config:
path: pages
logger_mode: info
middleware_config:
  status_page:
    status_mes_json_path: pages/err/status_code.json
    status_page_template_path: pages/err/index.html
